services:
  mongo:
    image: mongo:latest # version stable récente
    container_name: mongo-notes
    ports:
      - 27017:27017 # map le port local 27017 vers le container
    volumes:
      - data:/data/db # persistance des données
volumes:
  data:
