services:
  app:
    image: ghcr.io/cyril-fl/notes:latest
    container_name: notes-app
    ports:
      - 8880:3000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo-notes
    volumes:
      - data:/data/db
    restart: unless-stopped

volumes:
  data:
